name: 'Re-deploy'
description: 'A Github Action that Re-Deploys pythonanywhere-web-application'
inputs:
  HOST:
    description: 'Pythonanywhere host (EU/US), can be either eu.pythonanywhere.com or www.pythonanywhere.com (default)'
    default: 'www.pythonanywhere.com'
  USERNAME:
    description: 'Username for pythonanywhere'
    required: true
  API_TOKEN: 
    description: 'API token for pythonanywhere'
    required: true
  DOMAIN_NAME:
    description: 'Domain name of the webapp to reload'
    required: true
  CONSOLE_ID:
    description: 'Console id of the webapp created from'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
      shell: bash 

    - name: Update Repository
      run: |
        python src/update_repository.py
      uses: ./
    
    - name: Update Requirements
      run: |
        python src/update_requirements.py
      uses: ./
    
    - name: Reload Host
      run: |
        python src/reload_host.py
      uses: ./
