name: 'Re-Deploy Pythonanywhere Django API'
description: 'GitHub action to re-deploy a django webapp on pythonanywhere'
inputs:
  host:
    description: 'Pythonanywhere host (EU/US), can be either eu.pythonanywhere.com or www.pythonanywhere.com'
    required: true
  username:
    description: 'Username for pythonanywhere'
    required: true
  api_token: 
    description: 'API token for pythonanywhere'
    required: true
  domain_name:
    description: 'Domain name of the webapp to reload'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: refresh-cw
  color: green