name: PythonAnywhere Deployment

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 

    - name: Install requests library
      run: |
        python -m pip install requests

    - name: Do Job
      run: |
        python main.py
